/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author merlo
 */
public class jFrame_Personale extends javax.swing.JFrame {

    /**
     * Creates new form jFrame_Personale
     */
    public jFrame_Personale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Pers_Right = new javax.swing.JPanel();
        jButton_EliminaPersonale = new javax.swing.JButton();
        jButton_AddPersonale = new javax.swing.JButton();
        jButton_ModificaPersonale = new javax.swing.JButton();
        jPanel_Pers_Left = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Pers_Left = new javax.swing.JTable();
        jButton_Back_Pers = new javax.swing.JButton();
        jButton_Home_Pers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Pers_Right.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Pers_Right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_EliminaPersonale.setBackground(new java.awt.Color(255, 255, 255));
        jButton_EliminaPersonale.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_EliminaPersonale.setForeground(new java.awt.Color(51, 51, 51));
        jButton_EliminaPersonale.setText("elimina personale");
        
        jPanel_Pers_Right.add(jButton_EliminaPersonale, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 160, -1));

        jButton_AddPersonale.setBackground(new java.awt.Color(255, 255, 255));
        jButton_AddPersonale.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_AddPersonale.setForeground(new java.awt.Color(51, 51, 51));
        jButton_AddPersonale.setText("aggiungi personale");
        
        jPanel_Pers_Right.add(jButton_AddPersonale, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 160, -1));

        jButton_ModificaPersonale.setBackground(new java.awt.Color(255, 255, 255));
        jButton_ModificaPersonale.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_ModificaPersonale.setForeground(new java.awt.Color(51, 51, 51));
        jButton_ModificaPersonale.setText("modifica personale");
        
        jPanel_Pers_Right.add(jButton_ModificaPersonale, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 160, -1));

        getContentPane().add(jPanel_Pers_Right, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 500, 600));

        jPanel_Pers_Left.setBackground(new java.awt.Color(0, 153, 255));
        jPanel_Pers_Left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTable_Pers_Left.setBackground(new java.awt.Color(255, 255, 255));
        jTable_Pers_Left.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cognome", "Mansione", "Paga Oraria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Pers_Left);

        jPanel_Pers_Left.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jButton_Back_Pers.setBackground(new java.awt.Color(0, 153, 255));
        jButton_Back_Pers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Back.png"))); // NOI18N
        
        jPanel_Pers_Left.add(jButton_Back_Pers, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jButton_Home_Pers.setBackground(new java.awt.Color(0, 153, 255));
        jButton_Home_Pers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Home.png"))); // NOI18N
       
        jPanel_Pers_Left.add(jButton_Home_Pers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel_Pers_Left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

       public javax.swing.JButton getjButton_AddPersonale() {
		return jButton_AddPersonale;
	}

	public void setjButton_AddPersonale(javax.swing.JButton jButton_AddPersonale) {
		this.jButton_AddPersonale = jButton_AddPersonale;
	}

	public javax.swing.JButton getjButton_Back_Pers() {
		return jButton_Back_Pers;
	}

	public void setjButton_Back_Pers(javax.swing.JButton jButton_Back_Pers) {
		this.jButton_Back_Pers = jButton_Back_Pers;
	}

	public javax.swing.JButton getjButton_EliminaPersonale() {
		return jButton_EliminaPersonale;
	}

	public void setjButton_EliminaPersonale(javax.swing.JButton jButton_EliminaPersonale) {
		this.jButton_EliminaPersonale = jButton_EliminaPersonale;
	}

	public javax.swing.JButton getjButton_Home_Pers() {
		return jButton_Home_Pers;
	}

	public void setjButton_Home_Pers(javax.swing.JButton jButton_Home_Pers) {
		this.jButton_Home_Pers = jButton_Home_Pers;
	}

	public javax.swing.JButton getjButton_ModificaPersonale() {
		return jButton_ModificaPersonale;
	}

	public void setjButton_ModificaPersonale(javax.swing.JButton jButton_ModificaPersonale) {
		this.jButton_ModificaPersonale = jButton_ModificaPersonale;
	}

	public javax.swing.JTable getjTable_Pers_Left() {
		return jTable_Pers_Left;
	}

	public void setjTable_Pers_Left(javax.swing.JTable jTable_Pers_Left) {
		this.jTable_Pers_Left = jTable_Pers_Left;
	}



	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddPersonale;
    private javax.swing.JButton jButton_Back_Pers;
    private javax.swing.JButton jButton_EliminaPersonale;
    private javax.swing.JButton jButton_Home_Pers;
    private javax.swing.JButton jButton_ModificaPersonale;
    private javax.swing.JPanel jPanel_Pers_Left;
    private javax.swing.JPanel jPanel_Pers_Right;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Pers_Left;
    // End of variables declaration//GEN-END:variables
}
