/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Merlo
 */
public class jFrame_Cantiere extends javax.swing.JFrame {

    /**
     * Creates new form jFrame_Cantiere
     */
    public jFrame_Cantiere() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Cantiere = new javax.swing.JPanel();
        jButton_Home = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Materiali = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Personale = new javax.swing.JTable();
        jComboBox_Categoria = new javax.swing.JComboBox<>();
        jComboBox_Prodotto = new javax.swing.JComboBox<>();
        jTextField_Qta = new javax.swing.JTextField();
        jLabel_Qta = new javax.swing.JLabel();
        jComboBox_Personale = new javax.swing.JComboBox<>();
        jTextField_Nore = new javax.swing.JTextField();
        jLabel_Nore = new javax.swing.JLabel();
        jLabel_Desc_Lav = new javax.swing.JLabel();
        jTextField_Desc_Lav = new javax.swing.JTextField();
        jButton_Aggiungi = new javax.swing.JButton();
        jButton_Nuovo_Prod = new javax.swing.JButton();
        jButton_ToFattura = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App");
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);

        jPanel_Cantiere.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Cantiere.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Home.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons8-home-50.png"))); // NOI18N
        jPanel_Cantiere.add(jButton_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jButton_Back.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons8-back-50.png"))); // NOI18N
        jPanel_Cantiere.add(jButton_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jTable_Materiali.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Materiali);

        jPanel_Cantiere.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 210));

        jTable_Personale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_Personale);

        jPanel_Cantiere.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 210));

        jComboBox_Categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel_Cantiere.add(jComboBox_Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, -1, -1));

        jComboBox_Prodotto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel_Cantiere.add(jComboBox_Prodotto, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, -1, -1));

        jTextField_Qta.setBackground(new java.awt.Color(153, 153, 153));
        jTextField_Qta.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Qta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_QtaActionPerformed(evt);
            }
        });
        jPanel_Cantiere.add(jTextField_Qta, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 90, -1));

        jLabel_Qta.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_Qta.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Qta.setText("quantità");
        jPanel_Cantiere.add(jLabel_Qta, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, -1, -1));

        jComboBox_Personale.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel_Cantiere.add(jComboBox_Personale, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));

        jTextField_Nore.setBackground(new java.awt.Color(153, 153, 153));
        jTextField_Nore.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Nore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NoreActionPerformed(evt);
            }
        });
        jPanel_Cantiere.add(jTextField_Nore, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 90, -1));

        jLabel_Nore.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_Nore.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Nore.setText("numero ore");
        jPanel_Cantiere.add(jLabel_Nore, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, -1, -1));

        jLabel_Desc_Lav.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_Desc_Lav.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Desc_Lav.setText("descrizione lavoro");
        jPanel_Cantiere.add(jLabel_Desc_Lav, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, -1, -1));

        jTextField_Desc_Lav.setBackground(new java.awt.Color(153, 153, 153));
        jTextField_Desc_Lav.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Desc_Lav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Desc_LavActionPerformed(evt);
            }
        });
        jPanel_Cantiere.add(jTextField_Desc_Lav, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 360, 80));

        jButton_Aggiungi.setText("Aggiungi");
        jButton_Aggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AggiungiActionPerformed(evt);
            }
        });
        jPanel_Cantiere.add(jButton_Aggiungi, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 100, -1));

        jButton_Nuovo_Prod.setText("Nuovo Prodotto");
        jPanel_Cantiere.add(jButton_Nuovo_Prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, -1));

        jButton_ToFattura.setText("Fattura");
        jButton_ToFattura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ToFatturaActionPerformed(evt);
            }
        });
        jPanel_Cantiere.add(jButton_ToFattura, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Cantiere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Cantiere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_QtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_QtaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_QtaActionPerformed

    private void jTextField_NoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NoreActionPerformed

    private void jTextField_Desc_LavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Desc_LavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Desc_LavActionPerformed

    private void jButton_AggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AggiungiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_AggiungiActionPerformed

    private void jButton_ToFatturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ToFatturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_ToFatturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_Cantiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_Cantiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_Cantiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_Cantiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_Cantiere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Aggiungi;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Home;
    private javax.swing.JButton jButton_Nuovo_Prod;
    private javax.swing.JButton jButton_ToFattura;
    private javax.swing.JComboBox<String> jComboBox_Categoria;
    private javax.swing.JComboBox<String> jComboBox_Personale;
    private javax.swing.JComboBox<String> jComboBox_Prodotto;
    private javax.swing.JLabel jLabel_Desc_Lav;
    private javax.swing.JLabel jLabel_Nore;
    private javax.swing.JLabel jLabel_Qta;
    private javax.swing.JPanel jPanel_Cantiere;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Materiali;
    private javax.swing.JTable jTable_Personale;
    private javax.swing.JTextField jTextField_Desc_Lav;
    private javax.swing.JTextField jTextField_Nore;
    private javax.swing.JTextField jTextField_Qta;
    // End of variables declaration//GEN-END:variables
}
