/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.xml.crypto.Data;

/**
 *
 * @author Merlo
 */
public class jFrame_Cantiere extends javax.swing.JFrame {

	// da togliere, serviva a me per fare i test
	private  Object[][] data = {
            {"John", "Doe", 25},
            {"Jane", "Smith", 30},
            {"Bob", "Johnson", 28}
    };
	
    /**
     * Creates new form jFrame_Cantiere
     */
    public jFrame_Cantiere() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Cantiere_Left = new javax.swing.JPanel();
        jButton_Home_Cant = new javax.swing.JButton();
        jButton_Back_Cant = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Bot_Cant = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Top_Cant = new javax.swing.JTable();
        jPanel_Cantiere_Right = new javax.swing.JPanel();
        jComboBox_Pers_Cant = new javax.swing.JComboBox<>();
        jComboBox_Categoria_Cant = new javax.swing.JComboBox<>();
        jComboBox_Prodotto_Cant = new javax.swing.JComboBox<>();
        jButton_ToFAttura_Cant = new javax.swing.JButton();
        jButton_Aggiungi_Cant = new javax.swing.JButton();
        jButton_NuovoProd_Cant = new javax.swing.JButton();
        jTextField_Descrizione_Cant = new javax.swing.JTextField();
        jTextField_Quantita_Cant = new javax.swing.JTextField();
        jTextField_Nore_Cant = new javax.swing.JTextField();
        jLabel_Descrizione_Cant = new javax.swing.JLabel();
        jLabel_Nore_Cant = new javax.swing.JLabel();
        jLabel_Quantita_Cant = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Cantiere_Left.setBackground(new java.awt.Color(0, 153, 255));
        jPanel_Cantiere_Left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Home_Cant.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Home_Cant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons8-home-50.png"))); // NOI18N
        jPanel_Cantiere_Left.add(jButton_Home_Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton_Back_Cant.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Back_Cant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/icons8-back-50.png"))); // NOI18N
        jPanel_Cantiere_Left.add(jButton_Back_Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jTable_Bot_Cant.setBackground(new java.awt.Color(255, 255, 255));
        jTable_Bot_Cant.setBorder(null);
        jTable_Bot_Cant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "dipendente", "ore", "costo manodopera"
            }
        ));
        jScrollPane1.setViewportView(jTable_Bot_Cant);

        jPanel_Cantiere_Left.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 230));

        jTable_Top_Cant.setBackground(new java.awt.Color(255, 255, 255));
        jTable_Top_Cant.setBorder(null);
        jTable_Top_Cant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "quantità", "costo totale"
            }
        ));
        jScrollPane2.setViewportView(jTable_Top_Cant);

        jPanel_Cantiere_Left.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 220));

        getContentPane().add(jPanel_Cantiere_Left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 600));

        jPanel_Cantiere_Right.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Cantiere_Right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox_Pers_Cant.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Pers_Cant.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox_Pers_Cant.setMaximumRowCount(200);
        jComboBox_Pers_Cant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel_Cantiere_Right.add(jComboBox_Pers_Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 80, 30));

        jComboBox_Categoria_Cant.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Categoria_Cant.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox_Categoria_Cant.setMaximumRowCount(200);
        jComboBox_Categoria_Cant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel_Cantiere_Right.add(jComboBox_Categoria_Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 80, 30));

        jComboBox_Prodotto_Cant.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Prodotto_Cant.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox_Prodotto_Cant.setMaximumRowCount(200);
        jComboBox_Prodotto_Cant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel_Cantiere_Right.add(jComboBox_Prodotto_Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 80, 30));

        jButton_ToFAttura_Cant.setBackground(new java.awt.Color(255, 255, 255));
        jButton_ToFAttura_Cant.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_ToFAttura_Cant.setForeground(new java.awt.Color(51, 51, 51));
        jButton_ToFAttura_Cant.setText("fattura");
        jPanel_Cantiere_Right.add(jButton_ToFAttura_Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 180, -1));

        jButton_Aggiungi_Cant.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Aggiungi_Cant.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_Aggiungi_Cant.setForeground(new java.awt.Color(51, 51, 51));
        jButton_Aggiungi_Cant.setText("aggiungi");
        jButton_Aggiungi_Cant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Aggiungi_CantActionPerformed(evt);
            }
        });
        jPanel_Cantiere_Right.add(jButton_Aggiungi_Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 180, -1));

        jButton_NuovoProd_Cant.setBackground(new java.awt.Color(255, 255, 255));
        jButton_NuovoProd_Cant.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_NuovoProd_Cant.setForeground(new java.awt.Color(51, 51, 51));
        jButton_NuovoProd_Cant.setText("aggiungi nuovo prodotto");
        jPanel_Cantiere_Right.add(jButton_NuovoProd_Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        jTextField_Descrizione_Cant.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Descrizione_Cant.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTextField_Descrizione_Cant.setForeground(new java.awt.Color(0, 0, 0));
        jPanel_Cantiere_Right.add(jTextField_Descrizione_Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 380, 110));

        jTextField_Quantita_Cant.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Quantita_Cant.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTextField_Quantita_Cant.setForeground(new java.awt.Color(0, 0, 0));
        jPanel_Cantiere_Right.add(jTextField_Quantita_Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 120, -1));

        jTextField_Nore_Cant.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Nore_Cant.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jTextField_Nore_Cant.setForeground(new java.awt.Color(0, 0, 0));
        jPanel_Cantiere_Right.add(jTextField_Nore_Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 120, -1));

        jLabel_Descrizione_Cant.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_Descrizione_Cant.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Descrizione_Cant.setText("descrizione");
        jPanel_Cantiere_Right.add(jLabel_Descrizione_Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        jLabel_Nore_Cant.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_Nore_Cant.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Nore_Cant.setText("numero ore");
        jPanel_Cantiere_Right.add(jLabel_Nore_Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, 20));

        jLabel_Quantita_Cant.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_Quantita_Cant.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Quantita_Cant.setText("quantità");
        jPanel_Cantiere_Right.add(jLabel_Quantita_Cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        getContentPane().add(jPanel_Cantiere_Right, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 500, 600));

        pack();
        setLocationRelativeTo(null);
        populateTable(jTable_Top_Cant, data);
        populateTable(jTable_Bot_Cant, data);
    }// </editor-fold>//GEN-END:initComponents
    
    //populateTable(jTable_Top_Cant, data);
    //populateTable(jTable_Bot_Cant, data);
    public void populateTable(JTable table,Object[][] data)
    {
        DefaultTableModel tblmodel =  (DefaultTableModel)table.getModel();
        for (Object[] row : data) {     
            	tblmodel.addRow(row);
        }
    }

    private void jButton_Aggiungi_CantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Aggiungi_CantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Aggiungi_CantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame_Cantiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame_Cantiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame_Cantiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame_Cantiere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame_Cantiere().setVisible(true);
                
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Aggiungi_Cant;
    private javax.swing.JButton jButton_Back_Cant;
    private javax.swing.JButton jButton_Home_Cant;
    private javax.swing.JButton jButton_NuovoProd_Cant;
    private javax.swing.JButton jButton_ToFAttura_Cant;
    private javax.swing.JComboBox<String> jComboBox_Categoria_Cant;
    private javax.swing.JComboBox<String> jComboBox_Pers_Cant;
    private javax.swing.JComboBox<String> jComboBox_Prodotto_Cant;
    private javax.swing.JLabel jLabel_Descrizione_Cant;
    private javax.swing.JLabel jLabel_Nore_Cant;
    private javax.swing.JLabel jLabel_Quantita_Cant;
    private javax.swing.JPanel jPanel_Cantiere_Left;
    private javax.swing.JPanel jPanel_Cantiere_Right;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Bot_Cant;
    private javax.swing.JTable jTable_Top_Cant;
    private javax.swing.JTextField jTextField_Descrizione_Cant;
    private javax.swing.JTextField jTextField_Nore_Cant;
    private javax.swing.JTextField jTextField_Quantita_Cant;
    // End of variables declaration//GEN-END:variables
}
