/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import java.sql.SQLException;

import javax.swing.JComboBox;

import controller.Return_Avalaible_Data;
import database.DB;

/**
 *
 * @author Merlo
 */
public class JDialog_EliminaCategoria extends javax.swing.JDialog {
	private static String nomeUtente;
	private DB db;
	private Return_Avalaible_Data Avalaible_Data;

    /**
     * Creates new form JDialog_EliminaCategoria
     */
    public JDialog_EliminaCategoria(java.awt.Frame parent, boolean modal, String nomeUtente) {
        super(parent, modal);
        this.nomeUtente=nomeUtente;
        this.db= new DB(nomeUtente);
        this.Avalaible_Data= new Return_Avalaible_Data();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel_Categoria_POP = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton_EliminaCat_POP = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel_Categoria_POP1 = new javax.swing.JLabel();
        jLabel_Prezzo_POP1 = new javax.swing.JLabel();
        jLabel_Nome_POP1 = new javax.swing.JLabel();
        jLabel_Elimina_Categoria_POP = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_Categoria_POP = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Categoria_POP.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_Categoria_POP.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Categoria_POP.setText("Categoria");
        jPanel2.add(jLabel_Categoria_POP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 300));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_EliminaCat_POP.setBackground(new java.awt.Color(255, 255, 255));
        jButton_EliminaCat_POP.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_EliminaCat_POP.setForeground(new java.awt.Color(51, 51, 51));
        jButton_EliminaCat_POP.setText("Elimina");
        jButton_EliminaCat_POP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminaCat_POPActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_EliminaCat_POP, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 250, 100, -1));

        jPanel3.setBackground(new java.awt.Color(0, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        /*jLabel_Categoria_POP1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_Categoria_POP1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Categoria_POP1.setText("categoria");
        jPanel3.add(jLabel_Categoria_POP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));*/

        /*jLabel_Prezzo_POP1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_Prezzo_POP1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Prezzo_POP1.setText("prezzo unitario");
        jPanel3.add(jLabel_Prezzo_POP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));*/

        /*jLabel_Nome_POP1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel_Nome_POP1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Nome_POP1.setText("nome");
        jPanel3.add(jLabel_Nome_POP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));*/

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 300));

        jLabel_Elimina_Categoria_POP.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel_Elimina_Categoria_POP.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Elimina_Categoria_POP.setText("Elimina Categoria");
        jPanel1.add(jLabel_Elimina_Categoria_POP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/lineaBlu4.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jComboBox_Categoria_POP.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Categoria_POP.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jComboBox_Categoria_POP.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox_Categoria_POP.setMaximumRowCount(200);
        jComboBox_Categoria_POP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jComboBox_Categoria_POP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Categoria_POPActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_Categoria_POP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
        try {
			populatejComboBox(jComboBox_Categoria_POP, Avalaible_Data.ReadDataByListOfArrayToComboBoxCat(db.SelectCategoria()));
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }// </editor-fold>//GEN-END:initComponents

    public void populatejComboBox(JComboBox<String> comboBox,String[] items)
    {
    	for (String item : items) {
            comboBox.addItem(item);
        }
    }
    
    private void jButton_EliminaCat_POPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminaCat_POPActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_EliminaCat_POPActionPerformed

    private void jComboBox_Categoria_POPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Categoria_POPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_Categoria_POPActionPerformed

    public javax.swing.JComboBox<String> getjComboBox_Categoria_POP() {
		return jComboBox_Categoria_POP;
	}

	public void setjComboBox_Categoria_POP(javax.swing.JComboBox<String> jComboBox_Categoria_POP) {
		this.jComboBox_Categoria_POP = jComboBox_Categoria_POP;
	}

	/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialog_EliminaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialog_EliminaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialog_EliminaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialog_EliminaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialog_EliminaCategoria dialog = new JDialog_EliminaCategoria(new javax.swing.JFrame(), true, nomeUtente);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_EliminaCat_POP;
    private javax.swing.JComboBox<String> jComboBox_Categoria_POP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Categoria_POP;
    private javax.swing.JLabel jLabel_Categoria_POP1;
    private javax.swing.JLabel jLabel_Elimina_Categoria_POP;
    private javax.swing.JLabel jLabel_Nome_POP1;
    private javax.swing.JLabel jLabel_Prezzo_POP1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
